[functions]
  directory = "netlify/functions"

[build]
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm run dev:app"
  targetPort = 8080
  port = 8888

[[context.production.redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[context.production.redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
